### ISSUE TITLE
DOI with figshare and cite/search in Scholar or similar

### ISSUE THREAD

**Issue by maurolepore** [odealab/coralbook#4]
@melisacbl: Please write your findings here.

**Comment by melisacbl** [comment]
Hi @maurolepore and @odealab 

figshare seems to be a great place to publish the book. Materials you can upload include papers, figures, data, code, models, videos, posters (from conferences etc.), teaching materials, and powerpoint presentations. You can obtain a DOI for each work you upload (it doesn't need to be an actual paper. So you can get a DOI for a code you wrote/poster you presented at a conference/teaching material you use for a lecture), and they also allow for different versions. You can also reserve a DOI for a work that you are not ready to publish yet, and decide on what you want to make public and private (I still don't know too much about this).

Uploads are also searchable on google scholar/google in general (even simply typing figshare in google scholar will give you a whole list of materials both available on google scholar and figshare). If you click and view any one of the uploads, it readily provides you the citation for it (and allows you to export the citation with any citation programs you're using e.g. RefWorks, BibTex etc.). Anything you upload will also be licensed to whichever licensing format you choose (I'm not too familiar with licensing in general so I can't say much about it). (A good place to learn about suitable licences is this: http://choosealicense.com.)

And guess what, they are partnered with Github! so you can import your github projects and codes in and upload them (usually as codes). It is free to create an account and you're automatically given 20 gb of space and allowed to upload files up to 5gb in size. Apparently, you can create accounts for institutions (e.g. STRI) or publishers (Odealab?) but you will have to contact them to create that kind of account (though there seems to be a fee involved).

You can also create projects involving multiple collaborators in it. This means that, for example, we can create the coral book project and invite whoever we want as collaborators (as long as they have a figshare account) and anyone of us can upload a chapter, paper, etc to the project. Though it won't ultimately compile it into a book, at least there is a platform for consolidating them together. Another feature they have is collections, which is basically allowing people to "collect/bookmark" works of others that they like.

That is all I have so far. I've created an account (melisacbl) to experiment with it and everything seems pretty straightforward (even the ability to link your figshare account with Github). Personally, I think figshare is great and even the developers themselves are trying to make it as easy and accessible as possible for users. I think I'm sold. What do you think?

**Comment by odealab** [comment]
Hi @melisacbl,

You should now be able to view and change the book. Can you confirm?

Now that you have an account, I  was able to add you to the group of developers of the coralbook; the group name is odealab_coral and, so far, it includes @odealab, @maurolepore and @melisacbl.

Thanks for your great work! The system github+bookdown+figshare seems very promising! I think that we should try upload what we have to figshare. After making sure that it works as (you learned) it  should, then we can put some time into improving/tidying the content. 

I suggest we try replicate in figshare the same structure of administrator and collaborators that we have  now in the github repo and the bookdown accounts. This is, odealab is administrator and melisacbl and maurolepore are collaborators. We all have an account in figshare (I have  just opened one associated to maurolepore@gmail.com and  for odealab@gmail.com). @melisacbl, if you have  the time, can you  please see if  you can access odealab account and create a dummy project with me and you as collaborators? (I will send login details through email.) I will be out in the field most of today. I can try tomorrow or the day after.

We may need to emaill Aaron a digest of our findings  after we make sure all works as expected. He seems  to not monitor the emails of the odealab account.

Best,
Mauro

**Comment by odealab** [comment]
Hi  @melisacbl,

I have linked the github account  of  @odealab with figshare, and I created (not published) a figshare item for the coralbook repository, with all the source files to compile the book. Associated to the figshare item there is:

- a DOI: 10.6084/m9.figshare.4509005
It is reserved but not active until  the figshare item is published

- a private link: figshare.com/s/f2ea26c8f6e793e091b4.
This link can be used by non figshare users also. It allows sharing privately while the figshare  item remains unpublished.

The citation to the figshare item is this:
odea, lab (): coralbook. figshare.
https://dx.doi.org/10.6084/m9.figshare.4509005
Retrieved: 23 02, Jan 02, 2017 (GMT)

MY CONCLUSION
All this is very user friendly  and it looks great but I think that a figshare item for an entire github repo may be redundant. The github repo itself is almost all we need. Except it has no DOI but a version number. Instead, I believe figshare is useful to us for a .pdf version of the book.

@melisacbl, please share your last thoughts before we write a digest for Aaron.

Cheers,
M

**Comment by melisacbl** [comment]
Hi @maurolepore,

I can now view the coralbook on https://bookdown.org/odealab/coralbook2/

However, I can't seem to change (edit?) it. When I click on the button with the pencil, it opens a new tab saying page 404 error. From my profile on RStudio Connect, I managed to access https://bookdown.org/connect/#/apps/367/access and somehow added myself on the "Who can change this site" list.. not sure if I was supposed/allowed to do that but that didn't make any difference.

I have also created a dummy project called "test" under the @odealab figshare account and added you and I as collaborators.

I agree with your previous comment that it is redundant to publish the code, but definitely useful to publish the coralbook on figshare as a pdf to get the DOI.

Cheers,
Melisa

**Comment by maurolepore** [comment]
Hi @melisacbl,

I think all is good. That you can change the site of the coralbook on
bookdown means little. I think "changes" are limited to modifying the
profile of the  site, not the book itself. The bookdown site displays a
compiled  version of the book; from here, there is no access to the source
 files. To change the source of  the book, you need to work on the source
files on github and re-compile the book.

I have struggled with .pdf. It seems that I have problems with the software
(Mikatex) that compiles the .pdf. I plan to do a little ammendments to the
source code soon and then ask you to try compile a  .pdf from your PC. If
that works, it means that the source is OK and confirms that the problem is
my .pdf compiler. I will let you know.

Thanks for your work!
Mauro

Mauro Lepore (PhD)

Smithsonian Tropical Research Institute, Panama
Off +50721.28365 (Naos) .28442 (Gamboa); Wpp +61478096450; Mob +50765346475

**Comment by odealab** [comment]
Hi @melisacbl,

Can you try compile the .pdf now? Please do:
- pull the most recent  version of the repo (master branch) from github
(- to be neat, create a new  branch, say, "pdf".)
- go to the _Build_ tab, then _Build Book_ dropdown menu and hit bookdown::pdf_book. 

Tell me if  this works. I think that, as a result, the .pdf should be created  into the _book folder.

Cheers,
Mauro

**Comment by melisacbl** [comment]
Hi @maurolepore,

Unfortunately, I am at school now but do not have my laptop with me (I usually don't bring it to school and use campus computers instead while at school). So I can't create the pdf right now but I will do it when I get back home today after 4pm, if that is OK. Sorry about this!

Also, what you said about not being able to change elements of the book on bookdown.org makes a lot of sense. I should have realized that earlier.

Cheers,
Melisa
